services:

  cps_api:
    image: openjdk:17
    container_name: cps_api
    hostname: cps_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6794:6794"
    env_file:
      - .env
    networks:
      - tanda_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6794/cps/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    command: "java -jar /cps.jar"

networks:
  tanda_network:
    external: true